config/routes.rb
PinewoodDerby::Application.routes.draw do
  root to: 'board#welcome'
  get 'board' => 'board#status_board'
  get 'board/welcome' => 'board#welcome'
  get 'runs/:id/postpone' => 'runs#postpone'
  post 'heats/cancel_current' => 'heats#cancel_current'
  resource 'derby', only: [] do
    collection do
      get 'login'         => 'derby#login'
      post 'authenticate' => 'derby#authenticate'
      post 'reset'        => 'derby#reset'
    end
  end
  resources(:contestants) { member { post 'reactivate' } }
  resources :races, only: [:new, :index] { collection { put 'redo' } }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  has_many :runs, dependent: :destroy
  has_many :heats, through: :runs

  scope :ranked, -> do
    with_average_time.
    where('heats.sequence >= 0').
    order('average_time')
  end

  scope :with_average_time, -> do
    select('contestants.*, avg(runs.time) AS average_time').
    group('contestants.id').
    joins('LEFT JOIN runs ON runs.contestant_id = contestants.id LEFT JOIN heats ON heats.id = runs.heat_id')
  end

  validates :name, presence: true

  def self.next_suitable(options = {})
    exclude = Array(options[:exclude])
    exclude = [Contestant.new] if exclude.empty?
    exclude = exclude.map { |contestant| contestant.respond_to?(:id) ? contestant.id.to_i : contestant.to_i }
    lane = options[:lane].to_i
    max_runs_per_contestant = DerbyConfig.lane_count

    # select
    s = select('contestants.*')
    # filter
    s = s.where('contestants.id NOT IN (?)', exclude) if exclude.any?
    s = s.where("contestants.retired IS NULL OR contestants.retired = ?", false)
    s = s.group('contestants.id')
    s = s.joins('LEFT JOIN runs ON runs.contestant_id = contestants.id')
    s = s.having('count(DISTINCT heats.id) < ?', max_runs_per_contestant)
    s = s.joins("LEFT JOIN runs AS runs_in_lane ON runs.contestant_id = contestants.id AND runs.lane = #{lane}")
    s = s.having("count(runs_in_lane.id) = 0")
    # order
    s = s.joins('LEFT JOIN heats ON heats.id = runs.heat_id')
    s = s.joins("LEFT JOIN runs AS runs_with_chosen ON runs_with_chosen.heat_id = heats.id AND runs_with_chosen.contestant_id IN (#{exclude.join(',')})")
    s = s.select('count(runs_with_chosen.id) AS heat_count_with_chosen')
    s = s.select('count(DISTINCT heats.id) AS heat_count')
    s = s.select('avg(runs.time) AS average_run_time')
    s = s.order('heat_count_with_chosen, heat_count, average_run_time DESC, contestants.created_at')

    return s if options[:raw]
    s.first
  end

  def self.generate(i = 26)
    (?a..?z).to_a[0, i].map{|a|a.upcase + a*10}.each{|a|Contestant.create name: a}
  end

  def average_time
    average_time = self[:average_time] || calculate_average_time

    average_time.try :round, 4
  end

  def retire
    transaction do
      update_attributes! retired: true
      runs.upcoming.readonly(false).each &:postpone

      self
    end
  end

  def reactivate
    update_attributes! retired: false

    self
  end

private

  def calculate_average_time
    (self.class.ranked.where(id: id).first || {})[:average_time]
  end

end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  before_action :set_contestant, only: [:show, :edit, :update, :destroy, :reactivate]
  before_filter :require_admin, except: :index

  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.with_average_time.to_a.sort_by do |contestant|
      if contestant.average_time
        [contestant.average_time, contestant.name]
      else
        [99, contestant.name]
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contestants }
    end
  end

  # GET /contestants/1
  # GET /contestants/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/new
  # GET /contestants/new.json
  def new
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/1/edit
  def edit
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(contestant_params)

    respond_to do |format|
      if @contestant.save
        format.html { redirect_to new_contestant_path, notice: "#{@contestant.name} has been registered." }
        format.json { render json: @contestant, status: :created, location: @contestant }
      else
        format.html { render action: "new" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contestants/1
  # PATCH/PUT /contestants/1.json
  def update
    respond_to do |format|
      if @contestant.update(contestant_params)
        format.html { redirect_to contestants_path, notice: "#{@contestant.name} was updated" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.json
  def destroy
    @contestant.retire

    respond_to do |format|
      format.html { redirect_to contestants_path, notice: "#{@contestant.name} has retired" }
      format.json { head :no_content }
    end
  end

  # POST /contestants/1
  # DELETE /contestants/1.json
  def reactivate
    @contestant.reactivate

    respond_to do |format|
      format.html { redirect_to contestants_path, notice: "#{@contestant.name} was reactivated" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contestant
      @contestant = Contestant.find(params[:id])
    end

    # Use this method to whitelist the permissible parameters. Example:
    #   params.require(:person).permit(:name, :age)
    #
    # Also, you can specialize this method with per-user checking of permissible
    # attributes.
    def contestant_params
      params.require(:contestant).permit(:name, :retired)
    end
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/views/contestants/_form.html.erb
<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'First name', autocomplete: 'off' %>
  </div>
  <div class="actions">
    <%= f.submit 'Register' %>
  </div>
<% end %>

app/views/contestants/edit.html.erb
<h1>Editing contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

app/views/contestants/index.html.erb
<h1>Contestants</h1>

<table id="contestants">
  <% if @contestants.any? %>
    <thead>
      <tr>
        <th>Rank</th>
        <th>Name</th>
        <th>Average</th>
        <% DerbyConfig.lane_count.times do |i| %>
          <th>Round <%= i+1 %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>
  <% end %>

  <tbody>
    <% i = 0 %>
    <%= content_tag_for(:tr, @contestants, class: "contestant") do |contestant| %>
      <td class="rank">
        <%= i += 1 if contestant.average_time %>
      </td>
      <td class="<%= 'retired' if contestant.retired %>">
        <% if admin? %>
          <%= link_to contestant.name, edit_contestant_path(contestant) %>
        <% else %>
          <%= contestant.name %>
        <% end %>
      </td>
      <td>
        <%= contestant.average_time %>
      </td>
      <% DerbyConfig.lane_count.times do |i| %>
        <td><%= contestant.runs.complete[i].try :time %></td>
      <% end %>
      <td>
        <% if contestant.retired %>
          <%= link_to 'reactivate', reactivate_contestant_path(contestant), method: :post, class: 'retire', style: 'display: none' %>
        <% else %>
          <%= link_to 'retire', contestant, method: :delete, data: { confirm: "Are you sure? #{j contestant.name} will be taken out of the race." }, class: 'retire', style: 'display: none' %>
        <% end %>
      </td>
    <% end %>
  </tbody>
</table>

<br>

<% if admin? %>
  <%= link_to 'Register contestants', new_contestant_path, class: 'btn btn-primary' %>
  <%= link_to 'Reset derby', reset_derby_path, class: 'btn btn-danger pull-right', method: 'post', data: { confirm: 'Are you sure? This will clear out all data and start a new derby.' } %>
<% end %>

app/views/contestants/new.html.erb
<h2>Register a contestant</h2>

<%= render 'form' %>

<%= link_to 'Done registering', contestants_path %>

app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contestant.name %>
</p>

<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>