config/routes.rb
PinewoodDerby::Application.routes.draw do
  root to: 'board#welcome'
  get 'board' => 'board#status_board'
  get 'board/welcome' => 'board#welcome'
  get 'runs/:id/postpone' => 'runs#postpone'
  post 'heats/cancel_current' => 'heats#cancel_current'
  resource 'derby', only: [] do
    collection do
      get 'login'         => 'derby#login'
      post 'authenticate' => 'derby#authenticate'
      post 'reset'        => 'derby#reset'
    end
  end
  resources(:contestants) { member { post 'reactivate' } }
  resources :races, only: [:new, :index] { collection { put 'redo' } }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def welcome
    @url = BoardHelper.app_url(request)
  end

  def status_board
  end
end

app/helpers/board_helper.rb
module BoardHelper
  URL_CONFIG_FILE = Rails.root.join('config/url.conf')

  def self.app_url(request)
    configured_url || url_from_ip(request)
  end

private

  def self.configured_url
    url = File.exists?(URL_CONFIG_FILE) && File.read(URL_CONFIG_FILE)

    url.present? && url
  end

  def self.url_from_ip(request)
    (ip = local_ip) or return
    base = "http://#{local_ip}"
    port = request.port
    base += ":#{port}" unless 80 == port

    base
  end

  def self.local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1
      s.addr.last
    end
  rescue Errno::ENETUNREACH
    nil
  ensure
    Socket.do_not_reverse_lookup = orig
  end

  def self.column_width_split_into(column_count)
    layout_column_count = 12
    layout_column_count / column_count.to_i
  end

  def self.lane_column_width
    "span#{BoardHelper.column_width_split_into(DerbyConfig.lane_count)}"
  end
end

app/views/board/_forkme.html.erb
<% if defined?(mobile) && mobile %>
  <p><h6><a href="https://github.com/nilbus/pinewood-derby" target="_blank" class="hidden-desktop">Fork me on GitHub</a></h6></p>
<% else %>
  <a href="https://github.com/nilbus/pinewood-derby" target="_blank" class="visible-desktop">
    <%= image_tag "forkme_right_darkblue_121621.png", style: 'position: absolute; top: 40px; right: 0; border: 0;', alt: 'Fork me on GitHub' %>
  </a>
<% end %>

app/views/board/status_board.html.erb
<div id="dashboard">
  <div class="row-fluid">
    <div class="span8 pull-right no-left-margin">
      <div id="most-recent-heat">
        <div class="row-fluid">
          <h2 class="span12">
            Previous Heat
            <% if admin? %>
              <%= link_to 'redo', '#', id: 'redo', class: 'btn btn-danger', style: 'display: none' %>
            <% end %>
          </h2>
        </div>
        <div class="row-fluid lanes">
          <% DerbyConfig.lane_count.times do |i| %>
            <small class="<%= BoardHelper.lane_column_width %>">Lane <%= i + 1 %></small>
          <% end %>
        </div>
        <div class="row-fluid">
          <% DerbyConfig.lane_count.times do |i| %>
            <div class="<%= BoardHelper.lane_column_width %> lane<%= i+1 %>">
              <div class="name"></div>
              <div class="time"></div>
            </div>
          <% end %>
        </div>
      </div>

      <div id="upcoming-heats">
        <h2>
          Up next...
          <% if admin? %>
            <%= link_to 'Start the race!', '#', id: 'start-race', class: 'btn btn-success', style: 'display: none' %>
          <% end %>
        </h2>
        <div class="row-fluid">
          <% DerbyConfig.lane_count.times do |i| %>
            <div class="<%= BoardHelper.lane_column_width %>">
              <small>Lane<%= i + 1 %></small>
            </div>
          <% end %>
        </div>
        <% if admin? %>
          <i class="cancel-heat icon-remove-circle" style="opacity: 0;" title="Cancel heat"></i>
        <% end %>
        <div class="row-fluid next1">
          <% DerbyConfig.lane_count.times do |i| %>
            <div class="<%= BoardHelper.lane_column_width %> name lane<%= i + 1 %>"></div>
          <% end %>
        </div>
        <div class="row-fluid"><hr></div>
        <div class="row-fluid next2">
          <% DerbyConfig.lane_count.times do |i| %>
            <div class="<%= BoardHelper.lane_column_width %> name lane<%= i + 1 %>"></div>
          <% end %>
        </div>
        <div class="row-fluid"><hr></div>
        <div class="row-fluid next3">
          <% DerbyConfig.lane_count.times do |i| %>
            <div class="<%= BoardHelper.lane_column_width %> name lane<%= i + 1 %>"></div>
          <% end %>
        </div>
      </div>
    </div>

    <div id="standings" class="span4 pull-left no-left-margin">
      <h2>Standings</h2>
      <div class="contestants">
      </div>
    </div>
  </div>
</div>

app/views/board/welcome.html.erb
<%= render 'forkme' %>
<div class="jumbotron">
  <h2>It's race time...</h2>
  <h1>dooo your best!</h1>
  <p><%= link_to 'Watch the race', board_path, class: 'btn btn-large btn-success' %></p>
  <p class="derby-url">Connect to this app from other devices<p>
  <code class="derby-url"><%= @url || 'git dis thingy online furst' %></code>
  <% if DerbyConfig.admin_password %>
    <p><%= link_to 'Run the race', login_derby_path, class: 'btn btn-info' %></p>
  <% end %>
  <%= render 'forkme', mobile: true %>
</div>