config/routes.rb
PinewoodDerby::Application.routes.draw do
  root to: 'board#welcome'
  get 'board' => 'board#status_board'
  get 'board/welcome' => 'board#welcome'
  get 'runs/:id/postpone' => 'runs#postpone'
  post 'heats/cancel_current' => 'heats#cancel_current'
  resource 'derby', only: [] do
    collection do
      get 'login'         => 'derby#login'
      post 'authenticate' => 'derby#authenticate'
      post 'reset'        => 'derby#reset'
    end
  end
  resources(:contestants) { member { post 'reactivate' } }
  resources :races, only: [:new, :index] { collection { put 'redo' } }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<div id="faye-notification" class="alert alert-error" style="display: none"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinewoodDerby</title>
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="/favicon.png">
  <!-- icon credit: http://www.areskub.com/ sieze icon set -->
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'PinewoodDerby', root_path, class: 'brand' %>
        <div class="nav-collapse collapse pull-right">
          <ul class="nav">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Welcome', root_path %></li>
            <li class="<%= 'active' if current_page?(board_path) %>"><%= link_to 'Dashboard', board_path%></li>
            <li class="<%= 'active' if current_page?(contestants_path) %>"><%= link_to 'Contestants', contestants_path%></li>
            <!-- <li class="<%#= 'active' if current_page?(races_path) %>"><%#= link_to 'Races', races_path%></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container-fluid">

    <%= render 'layouts/messages' %>

    <%= yield %>

    <hr>
    <footer>
      <p class="chrome-frame-required alert alert-warning" style="display: none">
        PinewoodDerby requires <a href="http://www.google.com/chromeframe" target="_blank">Google Chrome Frame</a> for Internet Explorer.
        <br>
        Please install Chrome Frame to escape the Twilight Zone.
      </p>
    </footer>
  </div> <!-- /container -->
</body>
<%= javascript_tag do %>
  window.alerts = new Announcer({type: '<%= current_page?(board_path) ? "dashboard" : "alerts" %>', stats: <%= Dashboard.to_json.html_safe %>, admin: <%= !!admin? %>})
<% end %>
</html>